### ISSUE TITLE
Cannot GET / http://localhost:9005/ Docker version 20.10.2, build 2291f61

### ISSUE THREAD

**Issue by bertlandh** [qeeqbox/analyzer#10]
Dear qeeqbox team,

Greetings.

I followed the instructions on the wiki 

```
docker-compose -f docker-compose-dev.yml up --build
Then open http://127.0.0.1:8000/login/
```

and tried to spin up a docker instance but i am getting and error message. 

> Cannot GET /.

I am using a windows 10 pro box. 

Please see the output of the logs linked below

![image](https://user-images.githubusercontent.com/27841491/106389147-ef4a9080-63af-11eb-9d09-1da3052958f1.png)

![image](https://user-images.githubusercontent.com/27841491/106389165-fec9d980-63af-11eb-99e0-d9d2f72c50b6.png)

![image](https://user-images.githubusercontent.com/27841491/106389170-04272400-63b0-11eb-932b-1851b51efc62.png)

Please can you advise me further.
Thank you for your time.

-

**Comment by giga-a** [comment]
hey, thanks for submitting your first issue. I think your issue with [social-analyzer](https://github.com/qeeqbox/social-analyzer) not [analyzer](https://github.com/qeeqbox/analyzer)!

[social-analyzer](https://github.com/qeeqbox/social-analyzer) - API, CLI & Web App for analyzing & finding a person's profile across 300+ social media websites (Detections are updated regularly)

[analyzer](https://github.com/qeeqbox/analyzer) - Offline Threat Intelligence Analyzer for extracting features, artifacts and IoCs from Windows, Linux, Android, iPhone, Blackberry, macOS binaries, emails and more 

That being said, I am looking..

**Comment by bertlandh** [comment]
> hey, thanks for submitting your first issue. I think your issue with [social-analyzer](https://github.com/qeeqbox/social-analyzer) not [analyzer](https://github.com/qeeqbox/analyzer)!
> 
> 
> 
> [social-analyzer](https://github.com/qeeqbox/social-analyzer) - API, CLI & Web App for analyzing & finding a person's profile across 300+ social media websites (Detections are updated regularly)
> 
> 
> 
> [analyzer](https://github.com/qeeqbox/analyzer) - Offline Threat Intelligence Analyzer for extracting features, artifacts and IoCs from Windows, Linux, Android, iPhone, Blackberry, macOS binaries, emails and more 
> 
> 
> 
> That being said, I am looking..

Greetings sir. Thank you for your attention. If you need anything from me please let me know. Again sir, thank you for your attention.

**Comment by giga-a** [comment]
Hey, have you tried http://0.0.0.0:9005 ?

**Comment by giga-a** [comment]
Okay, how about this running the new CLI version?

```
pip install social-analyzer
```

**Comment by bertlandh** [comment]
> Okay, how about this running the new CLI version?
> 
> 
> 
> ```
> 
> pip install social-analyzer
> 
> ```

Thank you sir. I will try this and update you.
