### ISSUE TITLE
error build dockerfile

### ISSUE THREAD

**Issue by sephirothac** [qeeqbox/analyzer#12]
Hello, 

Thank you very much for your project, but since the last update of the dockerfile, the build is in error, here is the log of the build, again thank you for your help.

Sincerely sephirothac

Building service
Sending build context to Docker daemon  355.4MB
Step 1/12 : FROM ubuntu:latest
latest: Pulling from library/ubuntu
125a6e411906: Pull complete
Digest: sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d
Status: Downloaded newer image for ubuntu:latest
 ---> d2e4e1f51132
Step 2/12 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in 18a848fb721c
Removing intermediate container 18a848fb721c
 ---> ee5a1eaedfa0
Step 3/12 : RUN apt-get update && apt-get install -y python3 python3-pip curl libfuzzy-dev yara libmagic-dev libjansson-dev libssl-dev libffi-dev tesseract-ocr libtesseract-dev libssl-dev swig p7zip-full radare2 dmg2img snort
 ---> Running in e639009dbca9
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [150 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [149 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [68.8 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4653 B]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [259 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [153 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [117 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [4653 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [1202 B]
Fetched 21.2 MB in 2s (9474 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package radare2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'radare2' has no installation candidate
The command '/bin/sh -c apt-get update && apt-get install -y python3 python3-pip curl libfuzzy-dev yara libmagic-dev libjansson-dev libssl-dev libffi-dev tesseract-ocr libtesseract-dev libssl-dev swig p7zip-full radare2 dmg2img snort' returned a non-zero code: 100
ERROR: Service 'service' failed to build : Build failed

**Comment by giga-a** [comment]
Hey @sephirothac!  I'm looking..

**Comment by giga-a** [comment]
@sephirothac Fixed, let me know if the fix works or not

**Comment by sephirothac** [comment]
Hello [giga-a](https://github.com/giga-a), 

Thank you for your feedback, I have done the tests and everything is ok.

Thanks again.

**Comment by giga-a** [comment]
@giga-a Great, and feel free to share!
