### ISSUE TITLE
HybridAnalysis - Error API key missing

### ISSUE THREAD

**Issue by ghost** [qeeqbox/analyzer#7]
After installation completed and running without any problem i got this error after scan my website.

`HybridAnalysis

{
    "response_code": -1,
    "response": {
        "error": "API key missing"
    }
}`

**Comment by qeeqbox** [comment]
You need to write your API keys in analyzer/services/online/tokens.json

How to get API keys for the supported feeds:
https://www.hybrid-analysis.com/docs/api/v2
https://malshare.com/doc.php
https://onlinehelp.opswat.com/vault/Generate_an_API_key_from_Metadefender_Core.html
https://developers.virustotal.com/reference#getting-started

Will be adding new logic that checks if keys are provided or not in the next update

**Comment by qeeqbox** [comment]
Updated #https://github.com/qeeqbox/analyzer/commit/ffc02a7759dc0dfaba961f49416145380264e680

**Comment by qeeqbox** [comment]
Added AlienVault https://github.com/qeeqbox/analyzer/commit/240d93b98f0106b6609ea2b1aa083608692f7d90
