### ISSUE TITLE
Problem while make

### ISSUE THREAD

**Issue by arian-code** [qeeqbox/analyzer#9]
[ 85%] Building CXX object CMakeFiles/pcapfs.dir/src/virtualfiles/ssl.cpp.o
[ 88%] Building CXX object CMakeFiles/pcapfs.dir/src/virtualfiles/tcp.cpp.o
/home/testing/pcapFS/src/virtualfiles/tcp.cpp: In static member function ‘static std::vector<std::shared_ptr<pcapfs::File> > pcapfs::TcpFile::createVirtualFilesFromPcaps(const std::vector<std::shared_ptr<pcapfs::File> >&)’:
/home/testing/pcapFS/src/virtualfiles/tcp.cpp:205:99: error: invalid initialization of reference of type ‘const timeval&’ from expression of type ‘timespec’
             state.currentTimestamp = utils::convertTimeValToTimePoint(rawPacket.getPacketTimeStamp());
                                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /home/testing/pcapFS/src/virtualfiles/tcp.cpp:14:0:
/home/testing/pcapFS/src/virtualfiles/../utils.h:18:19: note: in passing argument 1 of ‘pcapfs::TimePoint pcapfs::utils::convertTimeValToTimePoint(const timeval&)’
         TimePoint convertTimeValToTimePoint(const timeval &tv);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~
CMakeFiles/pcapfs.dir/build.make:614: recipe for target 'CMakeFiles/pcapfs.dir/src/virtualfiles/tcp.cpp.o' failed
make[2]: *** [CMakeFiles/pcapfs.dir/src/virtualfiles/tcp.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/pcapfs.dir/all' failed
make[1]: *** [CMakeFiles/pcapfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qeeqbox** [comment]
1) Are you building this project? If so, how did you build the project?
2) Would you be able to send me the entire building outputs?

Based on your logs, It seems that you're having issues building pcapFS not this project
